language: java
sudo: enabled
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
os: linux
before_install:
  - chmod +x travis-before.sh
  - ./travis-before.sh
