language: java
sudo: enabled
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
os: linux
before_install:
  - |
    sudo apt-get install unzip
    wget -N http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux32.zip -P ~/Downloads
    unzip ~/Downloads/chromedriver_linux32.zip -d ~/Downloads
    chmod +x ~/Downloads/chromedriver
    sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
    sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
