language: java
sudo: enabled
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
os: linux
before_install:
  - |
    sudo apt-get install unzip
    wget -N http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip -P ~/Downloads
    unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
    chmod +x ~/Downloads/chromedriver
    sudo mkdir ~/selenium
    sudo mv -f ~/Downloads/chromedriver ~/selenium/chromedriver
    sudo ln -s ~/selenium/chromedriver /usr/local/bin/chromedriver
    sudo ln -s ~/selenium/chromedriver /usr/bin/chromedriver
